### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by hedeqiang** [JellyBool/translug#10]
Jelly 

![image](https://user-images.githubusercontent.com/31909061/70519092-5a1a8600-1b76-11ea-9ef2-4d5cce2e6156.png)

Laravel 6 版本，可能需要适配下，虽然可以通过 重写安装 helper 来实现
```
composer require laravel/helpers
```

**Comment by JellyBool** [comment]
Supported, update to `2.0.5` version should do the tricks.
