### ISSUE TITLE
Google Translation API

### ISSUE THREAD

**Issue by ghost** [JellyBool/translug#2]
加个 Google 的API，https://cloud.google.com/translate/v2/quickstart

服务器在国外用有道的就不好办了。

**Comment by JellyBool** [comment]
OK,我集成一下 Google 翻译 @littlehz

**Comment by JellyBool** [comment]
看了一下， Google 翻译的 API 需要先绑定信用卡才能用的吧。

**Comment by JellyBool** [comment]
没有绑定支付渠道的话，无法调用 Google 翻译的 API，所以我现在先关闭这个 issue，后面再看看。
