### ISSUE TITLE
RequestExceptioncURL error 60: SSL certificate problem:

### ISSUE THREAD

**Issue by mangnel** [JellyBool/translug#7]
(1/1) RequestExceptioncURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
--
in CurlFactory.php (line 187)
at CurlFactory::createRejection(object(EasyHandle), array('errno' => 60, 'error' => 'SSL certificate problem: unable to get local issuer certificate', 'url' => 'https://openapi.youdao.com/api?from=zh-CHS&to=EN&sign=4d0db5c10d8a618f72dc761ffe1c29d3&appKey=***&salt=f95c4b9205ed5f2e34dbd73fd0db5886&q=%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85+Laravel', 'content_type' => null, 'http_code' => 0, 'header_size' => 0, 'request_size' => 0, 'filetime' => -1, 'ssl_verify_result' => 1, 'redirect_count' => 0, 'total_time' => 0.094, 'namelookup_time' => 0.016, 'connect_time' => 0.047, 'pretransfer_time' => 0.0, 'size_upload' => 0.0, 'size_download' => 0.0, 'speed_download' => 0.0, 'speed_upload' => 0.0, 'download_content_length' => -1.0, 'upload_content_length' => -1.0, 'starttransfer_time' => 0.0, 'redirect_time' => 0.0, 'redirect_url' => '', 'primary_ip' => '220.181.76.82', 'certinfo' => array(), 'primary_port' => 443, 'local_ip' => '192.168.3.111', 'local_port' => 58532))in CurlFactory.php (line 150)
at CurlFactory::finishError(object(CurlHandler), object(EasyHandle), object(CurlFactory))in CurlFactory.php (line 103)
at CurlFactory::finish(object(CurlHandler), object(EasyHandle), object(CurlFactory))in CurlHandler.php (line 43)

安装了JellyBool/translug，在控制器中使用此包时，报错

**Comment by mangnel** [comment]
edit the following file in vendor/guzzlehttp/guzzle/src/Client.php

        $defaults = [
            'allow_redirects' => RedirectMiddleware::$defaultSettings,
            'http_errors'     => true,
            'decode_content'  => true,
            'verify'          => true,   //  将此处的值修改为 false
            'cookies'         => false
        ];

**Comment by JellyBool** [comment]
这个基本上就是环境的问题引起的，SSL 的配置，比如你的系统中 openssl 的问题等。

虽然改 guzzle 的源码可以解决问题，但是这个做法并不是推荐的做法。
