### ISSUE TITLE
有道api已更改，我更改之后，appKey无法读取env

### ISSUE THREAD

**Issue by Steinkuo** [JellyBool/translug#8]
private function getTranslateUrl($text)
    {
        $args = [
            'q' => $text,
            'from' => "zh-CHS",
            'to' => "EN",
            'appKey' => $this->config['appKey'],
            'salt' => rand(10000,99999),
        ];

        $args['sign'] = md5($this->config['appKey'] . $text . $args['salt'] . $this->config['appSecret']);
        $ret = $this->api.http_build_query($args);

        return $ret;
    }
这是我更改的内容，请帮忙指点

**Comment by JellyBool** [comment]
你的报错是什么？ @Steinkuo

**Comment by jasester** [comment]
本地开始的时候需要注意什么吗？
